spring:
  application:
    name: foodreport
  profiles:
    include:
    - private
    
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
  mvc:
    static-path-pattern: /uploads/**
  
  web:
    resources:
      static-locations: file:uploads/
      
mybatis:
  configuration:
    jdbc-type-for-null: VARCHAR
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.kh.foodreport.*.*.model.vo, com.kh.foodreport.*.*.model.dto, com.kh.foodreport.*.*.*.model.vo, com.kh.foodreport.*.*.*.model.dto, com.kh.foodreport.global.tag,
                        com.kh.foodreport.global.tag.model.dto.*
  mapper-locations: classpath:mapper/**/*.xml
  
server:
  port: 8081
  
springdoc:
  swagger-ui:
    path: /ui.html
